-- Migration 011 intentionally neutralized.
--
-- The original development fixture inserted a fixed Supabase Auth user and
-- password. Production-like databases must never create shared credentials.
-- Local/staging test users are provisioned out-of-band with environment-local
-- credentials and synthetic shop data.
